baseURL = "https://ericchung24.github.io/blog/"
languageCode = "zh-tw"
title = "Eric的程式勇者村"

defaultContentLanguage = "zh-tw"

# zh-tw 建議開 true，摘要/字數計算比較正常
hasCJKLanguage = true

[pagination]
pagerSize = 5
